### ISSUE TITLE
删除安装包后再次检查更新后，下载逻辑不正确

### ISSUE THREAD

**Issue by TrainNo110** [jjdxmashl/jjdxm_update#10]
下载后不安装，去文件目录把下载后的文件删除，再次检查更新时，提示最新安装包已下载
点击“立即更新”后不下载，而是直接安装（显然安装失败）

期望结果：提示“新版本大小：XXX”，点击“立即更新”后重新下载安装包

**Comment by jjdxmashl** [comment]
@TrainNo110  非常感谢指点错误哈！这个问题的确存在，下一版本进行修复。

**Comment by ysmintor** [comment]
我也发现这上问题了。另外我需要一些时间把网络方面的给切开。另外则是文字的变化也不对，我在Strings.xml文件看是对的，但下载无但没有安装，下一次打开的还是立即更新，不是立即安装。大家可以一起完善这个库。

**Comment by jjdxmashl** [comment]
@ysmintor  非常感觉指点错误哈

**Comment by TrainNo110** [comment]
还有一个问题，应该是和我提的属于同源问题
步骤
1、进客户端检查更新，然后下载，下载后无论安不安装，反正下载了
2、在服务端把对应version_code增加1，但是url保持不变
3、再次进入客户端检查更新，提示最新安装包已下载，并且点击“立即更新”后不下载

期望结果：提示“新版本大小：XXX”，点击“立即更新”后重新下载安装包

**Comment by jjdxmashl** [comment]
@TrainNo110 @ysmintor 这个问题已经修复1.0.5版本

**Comment by jjdxmashl** [comment]
@TrainNo110 
@ysmintor 
已经修复了，可以体验下新版本1.0.6
