### ISSUE TITLE
通知自定义

### ISSUE THREAD

**Issue by gjyaiya** [jjdxmashl/jjdxm_update#11]
下载完成后的Notifacation 内容能否自定义呢? 
_DownloadingService.java_中
`ntfBuilder.setSmallIcon(getApplicationInfo().icon)`
`.setContentTitle(getApplicationInfo().name)`
`.setContentText("下载完成，点击安装").setTicker("任务下载完成");`

另外'getApplicationInfo().name'这个拿不到应用名称吧

**Comment by jjdxmashl** [comment]
@gjyaiya 不好意思哈，通知栏自定义下个版本再再考虑接入，getApplicationInfo().name是可以拿到的

**Comment by jjdxmashl** [comment]
@gjyaiya 多谢指点错误，程序名称的确没有拿到，已经修改过来了，同时添加通知栏的自定义样式，可以体验下1.0.6版本的

**Comment by gjyaiya** [comment]
@jjdxmashl 好的呢, 等等试一下新版. 
另外提一个建议, 要是代码里的中文放到string里, 可以让用户自己定义和国际化就更好了 :)
