### ISSUE TITLE
我把Update自定义为UpdateBean,返回类型也改了，怎么还是提示UpdateBean cannot be cast to update?

### ISSUE THREAD

**Issue by s1168805219** [jjdxmashl/jjdxm_update#13]
`  
checkUrl 里面的json也改了，copy你的readme里的内容
@Override
                    public UpdateBean parse(String response) {

                        Log.d(TAG, "response=" + response);
                        Gson gson = new Gson();
                        UpdateBean updateBean = gson.fromJson(response, UpdateBean.class);
//                        Update update = gson.fromJson(response, Update.class);
                        return updateBean;
                    }
`

**Comment by jjdxmashl** [comment]
@s1168805219 我的sdk里面定义的一个Update对象，里面很多地方都有使用，Update里面的版本号，下载地址是必须的内容，
一种方法是你找到我项目里面所有用到的Update的，替换为你创建的，当然这个不建议，改动大；
另一种方法是，
Log.d(TAG, "response=" + response);
                    Gson gson = new Gson();
                    UpdateBean updateBean = gson.fromJson(response, UpdateBean.class);
你解析好了数据之后，创建一个Update对象，重新赋值给Update。
Update update = new Update();
update.setxxx(updateBean .getxxx());
...
最后返回
return update ;
