### ISSUE TITLE
在初始化UpdateConfig.initGet(this)中，你的意思是使用get请求，但是你的demo中写的是post请求，然而把post改成get请求后，比如说在autoupdate中点击更新按钮会返回“检测更新失败：Found"

### ISSUE THREAD

**Issue by mclmdream** [jjdxmashl/jjdxm_update#15]

**Comment by jjdxmashl** [comment]
@mclmdream 项目中initGet(this)方法里面的写错为post的了，是修改为get的，autoupdate这个还真是有这个问题，非常感谢指点意见哈，现在在着手这方面的修改，好了我会再发出来的。

**Comment by jdsjlzx** [comment]
是百度网站的问题。
可以修改如下：
private static String checkUrl = "http://www.qq.com";
private static String onlineUrl = "http://www.qq.com";

**Comment by jjdxmashl** [comment]
@mclmdream 已经修复了，可以体验下1.0.6版本的  @jdsjlzx 不是百度地址的问题，是其他的原因，貌似修复过来

**Comment by mclmdream** [comment]
初始化方法中的get请求依然有问题

**Comment by jdsjlzx** [comment]
@mclmdream 你要不要试试我的版本：https://github.com/jdsjlzx/umeng_update

**Comment by mclmdream** [comment]
@jdsjlzx 好的
