### ISSUE TITLE
貌似弹出框不能自定义啊

### ISSUE THREAD

**Issue by showdy** [jjdxmashl/jjdxm_update#2]

**Comment by jjdxmashl** [comment]
@showdy  是的，现在还不支持自定义弹出框的样式，如果你需要修改样式，可以考虑把jjdxm-update作为一个module依赖到你的项目去，你直接去修改样式。后期版本考虑加入这个设计

**Comment by jjdxmashl** [comment]
弹出框已经提供自定义样式方法，可以查看更新的项目readme.md文档，欢迎使用新版本

    compile 'com.dou361.update:jjdxm-update:1.0.4'
