### ISSUE TITLE
强制更新

### ISSUE THREAD

**Issue by ysmintor** [jjdxmashl/jjdxm_update#3]
快速加入强制更新吧！需要这个功能，样式应该增加自定义的方式。

**Comment by luyoulong** [comment]
这个大小好像不对吧 我输入1024000怎么是9MB啊

**Comment by jjdxmashl** [comment]
@ysmintor  好的哈
@luyoulong  欢迎指点为错误哈，这里的计算直接把小数点的去掉了，1024000是1000KB，10240000的是9.7MB左右为9MB，稍后修改下为保留两位的四舍五入吧

**Comment by luyoulong** [comment]
@jjdxmashl 谢谢了

**Comment by jjdxmashl** [comment]
@ysmintor @luyoulong 
1.强制更新
setCheckJsonParser返回内容解析中update.setForce(true为强制更新，false为正常更新);
或者
UpdateHelper.getInstance().setForced(true为强制更新，false为正常更新);
2.自定义样式
setDialogLayout(R.layout.custom_update_dialog)方法接收一个布局，主要案例中的布局样式里面的id为（jjdxm_update_content、jjdxm_update_id_ok、jjdxm_update_id_cancel）的view类型和id不能修改，其他的都可以修改或删除
3.计算包大小，保留两位的四舍五入，如果不需要显示包大小，update.setApkSize(0);传入为0即可。

具体的用法可以查看demo案例，或者更新的readme.md文档

**Comment by jjdxmashl** [comment]
1.0.4版本以后，不需要在清单文件中配置权限和一些服务的注册了，集成到aar中了的，只需要compile进来然后就是使用的事情了。
