### ISSUE TITLE
减少接入成本的建议

### ISSUE THREAD

**Issue by shakawwq** [jjdxmashl/jjdxm_update#4]
两个减少接入成本的建议：
1.权限以及组件注册直接写在library的manifest.xml

2.要是需要proguard，在library的build.gradle里添加

> 
    buildTypes {
        release {
            consumerProguardFiles 'proguard-rules.pro'
        }
    }
> 

就可以把library的proguard打入aar

**Comment by jjdxmashl** [comment]
@shakawwq  很好的建议，真的是集思广益啊，学习了哈，1.很久之前就打算这样做了的，一直是担心某些配置和主程序的会冲突之类的，后来才知道是白担心的，该冲突还是会冲突。2.特定去了解了，生成带Proguard配置的库，这样在引入的时候就直接从maven或者jcenter引入了，不需要在项目中配置混淆规则了，多贴心的功能。这里也记下参考的文章：http://blog.csdn.net/lihenair/article/details/51671803
后期版本考虑接入你的提建议。

**Comment by jjdxmashl** [comment]
@shakawwq 第一个建议已经接入项目中了，第二个混淆还是不太会配置，当前是没有加入混淆压缩那一块。等后期更加了解proguard再接进来吧，可以体验下新版本
    compile 'com.dou361.update:jjdxm-update:1.0.4'

**Comment by shakawwq** [comment]
@jjdxmashl 哈哈，新版好迅速，马上体验！
