### ISSUE TITLE
强制更新设置后仍旧在回调中为False

### ISSUE THREAD

**Issue by ysmintor** [jjdxmashl/jjdxm_update#5]
```java
UpdateHelper.getInstance()
                    /*.setUpdateType(UpdateType.checkupdate)
                    .setUpdateListener(new UpdateListener() {
                        @Override
                        public void noUpdate() {
                            Toast.makeText(mContext, "已经是最新版本了", Toast.LENGTH_LONG).show();
                        }

                        @Override
                        public void onCheckError(int code, String errorMsg) {
                            Toast.makeText(mContext, "检测更新失败：" + errorMsg, Toast.LENGTH_LONG).show();
                        }
                    })*/
                    .setForced(true)
                    .setForceListener(new ForceListener() {
                        @Override
                        public void onUserCancel(boolean force) {
                            Log.e(TAG, "onUserCancel: force = " + force);
                            if (force) {
                                //退出应用
                                finish();
                            }
                        }
                    })
                    .check(MainActivity.this);
```

log数据在用户取消后却没有退出应用，数据是`onUserCancel: force = false`

这是怎么回事啊？
@jjdxmashl 

我刚刚修改配置文件
```java
/**get方式请求的案例*/
    public static void initGet(Context context) {
        UpdateHelper.init(context);
        UpdateHelper.getInstance()
                // 可填：请求方式
                .setMethod(RequestType.get)
                // 必填：数据更新接口，该方法一定要在setDialogLayout的前面,因为这方法里面做了重置DialogLayout的操作
                .setCheckUrl(checkUrl)
                // 可填：自定义更新弹出的dialog的布局样式，主要案例中的布局样式里面的id为（jjdxm_update_content、jjdxm_update_id_ok、jjdxm_update_id_cancel）的view类型和id不能修改，其他的都可以修改或删除
                .setDialogLayout(R.layout.custom_update_dialog)
                // 必填：用于从数据更新接口获取的数据response中。解析出Update实例。以便框架内部处理
                .setCheckJsonParser(new ParseData() {
                    @Override
                    public Update parse(String response) {
                        // 此处模拟一个Update对象
                        Update update = new Update();
                        // 必填：此apk包的下载地址
                        update.setUpdateUrl(apkFile);
                        // 必填：此apk包的版本号
                        update.setVersionCode(2);
                        // 可填：此apk包的版本号
                        update.setApkSize(12400000);
                        // 必填：此apk包的版本名称
                        update.setVersionName("2.0");
                        // 可填：此apk包的更新内容
                        update.setUpdateContent("测试更新");
                        // 可填：此apk包是否为强制更新
                        update.setForce(true);
                        return update;
                    }
                });
    }
```
中修改了下下，倒是一进去的提示可以了。难道后面设置的setForce都没效果吗？但你前面说过

>遇到相同的配置时后调用的会覆盖先调用的，例如设置强制更新的配置

另外你的` .setMethod(RequestType.get)`这里写成了post了。

**Comment by jjdxmashl** [comment]
@ysmintor 

UpdateHelper.getInstance()
                    /*.setUpdateType(UpdateType.checkupdate)
                    .setUpdateListener(new UpdateListener() {
                        @Override
                        public void noUpdate() {
                            Toast.makeText(mContext, "已经是最新版本了", Toast.LENGTH_LONG).show();
                        }

                        @Override
                        public void onCheckError(int code, String errorMsg) {
                            Toast.makeText(mContext, "检测更新失败：" + errorMsg, Toast.LENGTH_LONG).show();
                        }
                    })*/
                    .setForced(true)
                    .setForceListener(new ForceListener() {
                        @Override
                        public void onUserCancel(boolean force) {
                            Log.e(TAG, "onUserCancel: force = " + force);
                            if (force) {
                                //退出应用
                                finish();
                            }
                        }
                    })
                    .check(MainActivity.this);

1.这一段配置中UpdateType.checkupdate为手动检测更新的，一般使用在点击检测按钮事件中使用的你把它注释后默认自动检测更新的。
2.然后强制更新的设置只能在初始化操作中设置，在init方法中就要配置了；
3.两种方式设置强制更新，①update.setforce(true); ② setForced(true);第一种只能在setCheckJsonParser方法中使用；第二种在setCheckJsonParser方法中或者setCheckJsonParser方法之后，也就是所说的后面会被覆盖的问题。
4.setMethod(RequestType.get)默认为get的，然后需要设置可以设置为post，你说写出post是什么问题

**Comment by ysmintor** [comment]
@jjdxmashl 
4. Demo中`initGet`中的`setMethod`中设置成了`RequestType.post`

**Comment by jjdxmashl** [comment]
@ysmintor 哦哦，多谢指点，理解了initGet的案例需要修改为get的

**Comment by ysmintor** [comment]
解决了我的问题，集成过程开始！
