### ISSUE TITLE
能否提供一个直接下载，通知栏有下载进度的方法

### ISSUE THREAD

**Issue by ysmintor** [jjdxmashl/jjdxm_update#6]
产品要在一个地方要显示更新内容和一个更新按钮（非dialog）。
我想直接使用本项目，而不是再开个service来控制通知栏的下载进度。主要是就没有显示更新dialog点确定而是点击立即更新按钮后直接开始在后台下载，当下载完成开始安装。

**Comment by jjdxmashl** [comment]
@ysmintor  不太理解你的意思，是不用下载完成的弹出框？还是其他的，
下载和通知栏提示进度，然后下载完成状态和安装的都在那个downserver类中，你可以参考去修改调用

**Comment by ysmintor** [comment]
@jjdxmashl 是不弹出更新提示。我已经和服务那知道要更新了，点击自定义更新的界面中的一个立即更新后开始下载，后面和点击更新dailog的更新按钮一样的效果。主要是手动检查更新时，产品不要弹出dialog，而是要自定义一个Activty里的。所以希望能提供一个这样的方法。

**Comment by jjdxmashl** [comment]
@ysmintor 你这种还是自己复制module到你的项目中，自己去修改吧，方法都在这个服务里面
https://github.com/jjdxmashl/jjdxm_update/blob/master/jjdxm-update/src/main/java/com/dou361/update/server/DownloadingService.java
调起开始下载的方法
![image](https://cloud.githubusercontent.com/assets/9255473/18376957/306461c4-7696-11e6-8377-d0a04e28707f.png)
然后下载完成后需要弹框就使用
 Intent intent = new Intent(mContext, UpdateDialogActivity.class);
                            intent.putExtra(UpdateConstants.DATA_UPDATE, update);
                            intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
                            intent.putExtra(UpdateConstants.DATA_ACTION, UpdateConstants.UPDATE_INSTALL);
                            intent.putExtra(UpdateConstants.SAVE_PATH, fil.getAbsolutePath());
                            startActivity(intent);
不需要弹框直接去安装就使用
 installApk(mContext, fil);
完成后的监听为
![image](https://cloud.githubusercontent.com/assets/9255473/18377000/84dad936-7696-11e6-8380-f0726281e0f1.png)

**Comment by ysmintor** [comment]
好的，我明白。其它相当于直接启动下载service进行更新，我就是想要这个方法。跳过了弹出dialog提示用户，因为我已经在当前页面显示了更新内容，就如同小米更新页一样，适合于手动更新。
