### ISSUE TITLE
checkUrl 与onlineUrl的区别

### ISSUE THREAD

**Issue by ysmintor** [jjdxmashl/jjdxm_update#7]
```java
    private static String checkUrl = "你的更新接口";
    private static String onlineUrl = "你的在线参数接口";
```

我看了下源码，没太明白这两个方法有什么区别，都接收同样的参数`ParseData jsonParser`，能解释一下吗？

**Comment by jjdxmashl** [comment]
@ysmintor  
1.checkUrl这个是用来检测是否有更新信息的接口的，专门用来更新应用使用；
2.onlineUrl这个是在线参数获取的一个接口，获取服务器设置的参数值，一般是用作在线配置使用，例如：
（1）服务器中配置是否要强制更新的一个参数force，服务器修改为true，APP启动后联网获取的就是true则强制更新，服务器修改为false，APP启动后联网获取的就是true则不强制更新。
（2）服务器定制等级参数level，服务器修改level为1显示什么，为2显示什么之类的。
只要用checkUrl接口就行了，onlineUrl就是提供一个接口访问和返回内容的解析，解析里面可以是一个参数或者多个参数，可以做一些在线配置的操作而已

**Comment by ysmintor** [comment]
@jjdxmashl 不是很能明白，那我还是只用checkUrl就可以。
