### ISSUE TITLE
建议把网络请求分离出来

### ISSUE THREAD

**Issue by ysmintor** [jjdxmashl/jjdxm_update#8]
比如在获取json更新时让用户自定义。我使用的是retrofit2，可能有些用户希望xutil，或者volley，okhttp等。反正让他们把网络请求的结果得到再设置就好了，这样也减小了这个库的大小，解耦更高。

**Comment by jjdxmashl** [comment]
@ysmintor 很好的建议，可以给点建议性的分离策略，当前还没有很好的思路，考虑后期版本拓展这方面的功能。

**Comment by jjdxmashl** [comment]
@ysmintor 已经分离出来了有兴趣可以了解下，1.0.6的版本

**Comment by ysmintor** [comment]
好的，最近都没有时间来看，上次就想花时间自己去实现的。
