### ISSUE TITLE
源码里面缺少  DownloadManager.class 和 SqliteManager.class ParamsManager.class

### ISSUE THREAD

**Issue by xibusuper** [jjdxmashl/jjdxm_update#9]
源码里面缺少  DownloadManager.class 和 SqliteManager.class ParamsManager.class 这3个文件

我引用 项目的 jar 包 ，  提示 找不到文件

麻烦能不能共享下

以前用友盟的更新插件，现在那个用不了了，实在是怀念，刚好搜索到你的项目，  折腾了  半天了还是 搞不定

**Comment by jjdxmashl** [comment]
@xibusuper 
抱歉，这个是因为这个库中依赖了另外的一个库，
![image](https://cloud.githubusercontent.com/assets/9255473/18416517/9a52fece-7849-11e6-9927-b581f8ec2749.png)

一般来说，都会自动去依赖进来的，有时候gradle没有那么智能，你手动添加下下面的依赖库

compile 'com.dou361.download:jjdxm-download:1.0.2'
